import React from 'react';

const Centralities = () => {
  return (



<div className="textlu">
<h2>Results</h2>
<p className="disco">

      <table>
      <thead>
        <tr>
          <th>Emotion</th>
          <th>In-Degree</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>joy</td>
          <td>0.215149</td>
        </tr>
        <tr>
          <td>fear</td>
          <td>0.514286</td>
        </tr>
        <tr>
          <td>surprise</td>
          <td>0.514286</td>
        </tr>
        <tr>
          <td>anger</td>
          <td>0.485714</td>
        </tr>
        <tr>
          <td>sadness</td>
          <td>0.342857</td>
        </tr>
        <tr>
          <td>love</td>
          <td>0.342857</td>
        </tr>
        <tr>
          <td>anticipation</td>
          <td>0.314286</td>
        </tr>
        <tr>
          <td>amazement</td>
          <td>0.314286</td>
        </tr>
        <tr>
          <td>contempt</td>
          <td>0.285714</td>
        </tr>
        <tr>
          <td>remorse</td>
          <td>0.200000</td>
        </tr>
      </tbody>
      </table>

      <table>
<thead>
  <tr>
    <th>Emotion</th>
    <th>Out-Degree</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>fear</td>
    <td>0.571429</td>
  </tr>
  <tr>
    <td>surprise</td>
    <td>0.514286</td>
  </tr>
  <tr>
    <td>anger</td>
    <td>0.485714</td>
  </tr>
  <tr>
    <td>love</td>
    <td>0.428571</td>
  </tr>
  <tr>
    <td>sadness</td>
    <td>0.428571</td>
  </tr>
  <tr>
    <td>joy</td>
    <td>0.400000</td>
  </tr>
  <tr>
    <td>amazement</td>
    <td>0.400000</td>
  </tr>
  <tr>
    <td>anticipation</td>
    <td>0.342857</td>
  </tr>
  <tr>
    <td>despair</td>
    <td>0.285714</td>
  </tr>
  <tr>
    <td>remorse</td>
    <td>0.285714</td>
  </tr>
</tbody>
</table>
<br></br>
      <table>
        <thead>
          <tr>
            <th>Emotion</th>
            <th>Betweenness</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>fear</td>
            <td>0.215149</td>
          </tr>
          <tr>
            <td>surprise</td>
            <td>0.136048</td>
          </tr>
          <tr>
            <td>joy</td>
            <td>0.121393</td>
          </tr>
          <tr>
            <td>anger</td>
            <td>0.086234</td>
          </tr>
          <tr>
            <td>love</td>
            <td>0.066726</td>
          </tr>
          <tr>
            <td>amazement</td>
            <td>0.065281</td>
          </tr>
          <tr>
            <td>anticipation</td>
            <td>0.057412</td>
          </tr>
          <tr>
            <td>sadness</td>
            <td>0.045336</td>
          </tr>
          <tr>
            <td>despair</td>
            <td>0.042037</td>
          </tr>
          <tr>
            <td>trust</td>
            <td>0.029848</td>
          </tr>


        </tbody>
      </table>

      <table>
      <thead>
        <tr>
          <th>Emotion</th>
          <th>Closeness</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>joy</td>
          <td>0.610159</td>
        </tr>
        <tr>
          <td>surprise</td>
          <td>0.596894</td>
        </tr>
        <tr>
          <td>fear</td>
          <td>0.584195</td>
        </tr>
        <tr>
          <td>sadness</td>
          <td>0.528022</td>
        </tr>
        <tr>
          <td>love</td>
          <td>0.518059</td>
        </tr>
        <tr>
          <td>anticipation</td>
          <td>0.508466</td>
        </tr>
        <tr>
          <td>amazement</td>
          <td>0.508466</td>
        </tr>
        <tr>
          <td>anger</td>
          <td>0.499221</td>
        </tr>
        <tr>
          <td>remorse</td>
          <td>0.450117</td>
        </tr>
        <tr>
          <td>serenity</td>
          <td>0.442857</td>
        </tr>
      </tbody>
      </table>
</p>
</div>


  );
};

export default Centralities;
